#!/bin/bash

sudo libreoffice --headless --convert-to csv ../../RAMA/06RAMA/2006NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/06RAMA/2006O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/06RAMA/2006SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/06RAMA/2006PM25.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/06RAMA/2006CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/06RAMA/2006PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/06RAMA/2006NO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/06RAMA/2006NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/15RAMA/2015PMCO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/15RAMA/2015SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/15RAMA/2015NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/15RAMA/2015PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/15RAMA/2015CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/15RAMA/2015O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/15RAMA/2015NO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/15RAMA/2015PM25.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/15RAMA/2015NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/87RAMA/1987CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/87RAMA/1987NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/87RAMA/1987SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/87RAMA/1987NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/87RAMA/1987O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/01RAMA/2001CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/01RAMA/2001NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/01RAMA/2001SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/01RAMA/2001NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/01RAMA/2001PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/01RAMA/2001O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/05RAMA/2005PM25.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/05RAMA/2005NO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/05RAMA/2005SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/05RAMA/2005PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/05RAMA/2005NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/05RAMA/2005O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/05RAMA/2005CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/05RAMA/2005NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/86RAMA/1986CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/86RAMA/1986O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/86RAMA/1986NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/86RAMA/1986SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/86RAMA/1986NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/88RAMA/1988NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/88RAMA/1988NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/88RAMA/1988SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/88RAMA/1988CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/88RAMA/1988O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/14RAMA/2014NO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/14RAMA/2014SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/14RAMA/2014PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/14RAMA/2014PM25.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/14RAMA/2014NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/14RAMA/2014O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/14RAMA/2014NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/14RAMA/2014CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/14RAMA/2014PMCO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/03RAMA/2003SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/03RAMA/2003NO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/03RAMA/2003PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/03RAMA/2003CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/03RAMA/2003O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/03RAMA/2003NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/03RAMA/2003PM25.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/03RAMA/2003NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/92RAMA/1992O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/92RAMA/1992NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/92RAMA/1992NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/92RAMA/1992CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/92RAMA/1992SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/95RAMA/1995NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/95RAMA/1995PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/95RAMA/1995CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/95RAMA/1995NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/95RAMA/1995O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/95RAMA/1995SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/11RAMA/2011CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/11RAMA/2011NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/11RAMA/2011PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/11RAMA/2011NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/11RAMA/2011NO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/11RAMA/2011O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/11RAMA/2011PM25.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/11RAMA/2011PMCO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/11RAMA/2011SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/02RAMA/2002SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/02RAMA/2002CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/02RAMA/2002O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/02RAMA/2002NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/02RAMA/2002PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/02RAMA/2002NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/10RAMA/2010SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/10RAMA/2010NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/10RAMA/2010O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/10RAMA/2010PM25.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/10RAMA/2010PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/10RAMA/2010CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/10RAMA/2010NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/10RAMA/2010NO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/91RAMA/1991O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/91RAMA/1991CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/91RAMA/1991SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/91RAMA/1991NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/91RAMA/1991NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/07RAMA/2007PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/07RAMA/2007NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/07RAMA/2007O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/07RAMA/2007PM25.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/07RAMA/2007SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/07RAMA/2007CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/07RAMA/2007NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/07RAMA/2007NO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/97RAMA/1997PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/97RAMA/1997CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/97RAMA/1997SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/97RAMA/1997NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/97RAMA/1997NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/97RAMA/1997O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/98RAMA/1998NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/98RAMA/1998PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/98RAMA/1998NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/98RAMA/1998O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/98RAMA/1998CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/98RAMA/1998SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/08RAMA/2008NO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/08RAMA/2008NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/08RAMA/2008CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/08RAMA/2008PM25.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/08RAMA/2008NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/08RAMA/2008O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/08RAMA/2008SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/08RAMA/2008PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/89RAMA/1989NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/89RAMA/1989O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/89RAMA/1989CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/89RAMA/1989SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/89RAMA/1989NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/04RAMA/2004SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/04RAMA/2004CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/04RAMA/2004NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/04RAMA/2004PM25.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/04RAMA/2004PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/04RAMA/2004NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/04RAMA/2004NO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/04RAMA/2004O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/90RAMA/1990NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/90RAMA/1990CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/90RAMA/1990SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/90RAMA/1990NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/90RAMA/1990O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/13RAMA/2013PM25.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/13RAMA/2013NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/13RAMA/2013PMCO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/13RAMA/2013CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/13RAMA/2013NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/13RAMA/2013NO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/13RAMA/2013SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/13RAMA/2013O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/13RAMA/2013PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/12RAMA/2012SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/12RAMA/2012NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/12RAMA/2012PM25.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/12RAMA/2012NO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/12RAMA/2012O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/12RAMA/2012NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/12RAMA/2012CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/12RAMA/2012PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/12RAMA/2012PMCO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/09RAMA/2009NO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/09RAMA/2009O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/09RAMA/2009CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/09RAMA/2009PM25.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/09RAMA/2009SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/09RAMA/2009PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/09RAMA/2009NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/09RAMA/2009NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/94RAMA/1994SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/94RAMA/1994O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/94RAMA/1994CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/94RAMA/1994NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/94RAMA/1994NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/96RAMA/1996NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/96RAMA/1996O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/96RAMA/1996CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/96RAMA/1996SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/96RAMA/1996NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/96RAMA/1996PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/00RAMA/2000CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/00RAMA/2000SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/00RAMA/2000NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/00RAMA/2000O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/00RAMA/2000PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/00RAMA/2000NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/16RAMA/2016PMCO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/16RAMA/2016PM10.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/16RAMA/2016CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/16RAMA/2016O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/16RAMA/2016SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/16RAMA/2016NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/16RAMA/2016NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/16RAMA/2016PM25.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/16RAMA/2016NO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/93RAMA/1993SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/93RAMA/1993NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/93RAMA/1993NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/93RAMA/1993CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/93RAMA/1993O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/99RAMA/1999SO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/99RAMA/1999CO.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/99RAMA/1999O3.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/99RAMA/1999NOX.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/99RAMA/1999NO2.xls --outdir ../../RAMA_CSV
sudo libreoffice --headless --convert-to csv ../../RAMA/99RAMA/1999PM10.xls --outdir ../../RAMA_CSV
